FROM alpine:3.15 as jdd-build

RUN apk add --no-cache tzdata nginx php7-fpm php7-curl php7-json
RUN mkdir -p /var/www/html && chmod -R 755 /var/www/html
COPY . /var/www/html/
RUN mkdir -p /var/www/html/comparisons && chmod 777 /var/www/html/comparisons
RUN chown -R nginx:nginx /var/www/html && rm -f /etc/nginx/http.d/*
ADD nginx.conf /etc/nginx/
ADD entrypoint.sh /

FROM scratch
COPY --from=jdd-build / /
ENTRYPOINT ["/entrypoint.sh"]
